export const ACTIVITIES_REQUEST = 'activities-request'
export const ACTIVITIES_SUCCESS = 'activities-success'
export const ACTIVITIES_FAILURE = 'activities-failure'
export const ACTIVITY_GET_REQUEST = 'activity-get-request'
export const ACTIVITY_GET_SUCCESS = 'activity-get-success'
export const ACTIVITY_GET_FAILURE = 'activity-get-failure'
export const ACTIVITY_SAVE_REQUEST = 'activity-save-request'
export const ACTIVITY_SAVE_SUCCESS = 'activity-save-success'
export const ACTIVITY_SAVE_FAILURE = 'activity-save-failure'
export const ACTIVITY_SAVE_CLEAR = 'activity-save-clear'
export const ACTIVITY_UPDATE_REQUEST = 'activity-update-request'
export const ACTIVITY_UPDATE_SUCCESS = 'activity-update-success'
export const ACTIVITY_UPDATE_FAILURE = 'activity-update-failure'
export const ACTIVITY_DELETE_REQUEST = 'activity-delete-request'
export const ACTIVITY_DELETE_SUCCESS = 'activity-delete-success'
export const ACTIVITY_DELETE_FAILURE = 'activity-delete-failure'

export const FIELD_SET = 'field-set'