export const TASKS_REQUEST = 'tasks-request'
export const TASKS_SUCCESS = 'tasks-success'
export const TASKS_FAILURE = 'tasks-failure'
export const TASK_GET_REQUEST = 'task-get-request'
export const TASK_GET_SUCCESS = 'task-get-success'
export const TASK_GET_FAILURE = 'task-get-failure'
export const TASK_SAVE_REQUEST = 'task-save-request'
export const TASK_SAVE_SUCCESS = 'task-save-success'
export const TASK_SAVE_FAILURE = 'task-save-failure'
export const TASK_SAVE_CLEAR = 'task-save-clear'
export const TASK_UPDATE_REQUEST = 'task-update-request'
export const TASK_UPDATE_SUCCESS = 'task-update-success'
export const TASK_UPDATE_FAILURE = 'task-update-failure'
export const TASK_DELETE_REQUEST = 'task-delete-request'
export const TASK_DELETE_SUCCESS = 'task-delete-success'
export const TASK_DELETE_FAILURE = 'task-delete-failure'

export const CURRENT_TASK_FIELD_SET = 'current-task-field-set'
export const CURRENT_TASK_TYPE_SET = 'current-task-type-set'

//Constantes especificas del tipo de tarea Multiple Choice
export const MC_TASK_OPTION_ADD = 'mc-task-option-add'
export const MC_TASK_OPTION_UPDATE = 'mc-task-option-update'